NODE_ENV={{NODE_ENV}}
PORT={{PORT}}
DB_HOST={{DB_HOST}}
DB_PORT={{DB_PORT}}
DB_USER={{DB_USER}}
DB_PASSWORD={{DB_PASSWORD}}
DB_NAME={{DB_NAME}}

CORS_ORIGIN={{CORS_ORIGIN}}
WEB_PUBLIC_ORIGIN={{WEB_PUBLIC_ORIGIN}}
WEB_BASE_PATH={{WEB_BASE_PATH}}
NEXT_PUBLIC_BASE_PATH={{NEXT_PUBLIC_BASE_PATH}}

JWT_SECRET={{JWT_SECRET}}
REQUIRE_AUTH={{REQUIRE_AUTH}}

UPLOAD_DRIVER={{UPLOAD_DRIVER}}
UPLOAD_DIR={{UPLOAD_DIR}}

GOOGLE_CLIENT_ID={{GOOGLE_CLIENT_ID}}
GOOGLE_CLIENT_SECRET={{GOOGLE_CLIENT_SECRET}}
GOOGLE_REDIRECT_URI={{GOOGLE_REDIRECT_URI}}
GOOGLE_DRIVE_REDIRECT_URI={{GOOGLE_DRIVE_REDIRECT_URI}}
API_PUBLIC_URL={{API_PUBLIC_URL}}

PAYMENT_PROVIDER={{PAYMENT_PROVIDER}}
PAYMENT_AUTO_COMPLETE={{PAYMENT_AUTO_COMPLETE}}
PAYMENT_WEBHOOK_SECRET={{PAYMENT_WEBHOOK_SECRET}}
SUBSCRIPTION_PRO_PRICE_INR={{SUBSCRIPTION_PRO_PRICE_INR}}
RAZORPAY_KEY_ID={{RAZORPAY_KEY_ID}}
RAZORPAY_KEY_SECRET={{RAZORPAY_KEY_SECRET}}
RAZORPAY_WEBHOOK_SECRET={{RAZORPAY_WEBHOOK_SECRET}}
