/**
 * PM2 ecosystem — JustX project {{PROJECT_ID}}
 * Generated by deploy framework; do not edit by hand on the server.
 */
module.exports = {
  apps: [
    {
      name: "justx-{{PROJECT_ID}}-api",
      cwd: "{{RELEASE_DIR}}",
      script: "npm",
      args: "run start -w server",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
        PORT: "{{API_PORT}}",
        WEB_BASE_PATH: "{{BASE_PATH}}",
      },
      env_file: "{{ENV_FILE}}",
      max_memory_restart: "512M",
      time: true,
      out_file: "{{LOG_DIR}}/api-out.log",
      error_file: "{{LOG_DIR}}/api-error.log",
      merge_logs: true,
      autorestart: true,
    },
    {
      name: "justx-{{PROJECT_ID}}-web",
      cwd: "{{RELEASE_DIR}}",
      script: "npm",
      args: "run start -w web -- -p {{WEB_PORT}}",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
        PORT: "{{WEB_PORT}}",
        NEXT_PUBLIC_BASE_PATH: "{{BASE_PATH}}",
        WEB_BASE_PATH: "{{BASE_PATH}}",
      },
      max_memory_restart: "512M",
      time: true,
      out_file: "{{LOG_DIR}}/web-out.log",
      error_file: "{{LOG_DIR}}/web-error.log",
      merge_logs: true,
      autorestart: true,
    },
  ],
};
