#!/usr/bin/env bash
# Create nginx htpasswd for Grafana front-door basic auth (recommended).
# Run on the VPS as deploy (needs sudo for /etc/nginx paths).
#
# Usage:
#   bash /var/www/jbt/deploy/observability/scripts/setup-grafana-basic-auth.sh
#   # or with username:
#   bash …/setup-grafana-basic-auth.sh grafanaops
#
set -euo pipefail

USER_NAME="${1:-grafanaops}"
HTPASSWD_FILE="${HTPASSWD_FILE:-/etc/nginx/.htpasswd-grafana}"
NGINX_SNIPPET="${NGINX_SNIPPET:-/etc/nginx/snippets/grafana-basic-auth.conf}"

if ! command -v htpasswd >/dev/null 2>&1; then
  echo "Installing apache2-utils (htpasswd)…"
  sudo apt-get update -qq
  sudo apt-get install -y apache2-utils
fi

echo "Creating/updating ${HTPASSWD_FILE} for user: ${USER_NAME}"
if [[ -f "${HTPASSWD_FILE}" ]]; then
  sudo htpasswd "${HTPASSWD_FILE}" "${USER_NAME}"
else
  sudo htpasswd -c "${HTPASSWD_FILE}" "${USER_NAME}"
fi
sudo chmod 640 "${HTPASSWD_FILE}"
sudo chown root:www-data "${HTPASSWD_FILE}" 2>/dev/null || sudo chown root:nginx "${HTPASSWD_FILE}" 2>/dev/null || true

sudo tee "${NGINX_SNIPPET}" >/dev/null <<EOF
# Generated by setup-grafana-basic-auth.sh — include inside location /grafana/
auth_basic "Grafana";
auth_basic_user_file ${HTPASSWD_FILE};
EOF

echo
echo "Snippet written to ${NGINX_SNIPPET}"
echo "Add inside your HTTPS location /grafana/ { … } block (before proxy_pass):"
echo "    include ${NGINX_SNIPPET};"
echo
echo "Then:"
echo "  sudo nginx -t && sudo systemctl reload nginx"
echo
echo "Browser will prompt for basic auth, then Grafana login (admin / GF_SECURITY_ADMIN_PASSWORD)."
