-- TOTP MFA for users (Owner/Admin recommended).
CREATE TABLE IF NOT EXISTS user_mfa (
  user_id INT UNSIGNED NOT NULL,
  secret_enc VARCHAR(512) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  confirmed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
