# Auto-generated by JustX deploy — shared server for {{DOMAIN}}
# Project locations: /etc/nginx/justx.d/{{DOMAIN_SLUG}}/*.conf
# Canonical public URL example: https://justxsystems.com/jbt/

limit_req_zone $binary_remote_addr zone=justx_global_limit:20m rate=20r/s;

server {
    listen 80;
    listen [::]:80;
    server_name {{DOMAIN}} {{DOMAIN_ALT}};

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
    }

    location / {
        return 301 https://{{DOMAIN}}$request_uri;
    }
}

# www → apex (canonical host)
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{DOMAIN_ALT}};

    ssl_certificate     /etc/letsencrypt/live/{{CERT_NAME}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{CERT_NAME}}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://{{DOMAIN}}$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{DOMAIN}};

    ssl_certificate     /etc/letsencrypt/live/{{CERT_NAME}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{CERT_NAME}}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;

    access_log /var/log/deployments/nginx-{{DOMAIN_SLUG}}-access.log;
    error_log  /var/log/deployments/nginx-{{DOMAIN_SLUG}}-error.log warn;

    client_max_body_size 25m;

    include /etc/nginx/justx.d/{{DOMAIN_SLUG}}/*.conf;

    location = / {
        root /var/www/html;
        try_files /index.html =404;
    }
}
